topic.name.property=people

#logging.level.org.springframework.boot.autoconfigure.logging=DEBUG
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.properties.specific.avro.reader=true
spring.kafka.properties.schema.registry.url=http://localhost:8085
spring.kafka.properties.json.type.mapping= People: common.metadata.People

## Endpoints to expose
management.endpoints.web.exposure.include=prometheus,health,info

# Exceções recuperáveis
app.kafka.dlt.exceptions.retrievable[0]=java.net.ConnectException
app.kafka.dlt.exceptions.retrievable[1]=java.net.UnknownHostException

# Exceções não-recuperáveis
app.kafka.dlt.exceptions.irretrievable[0]=org.apache.avro.AvroMissingFieldException
app.kafka.dlt.exceptions.irretrievable[1]=java.lang.NullPointerException

# Para provocar atraso no processmento de retentativa
app.kafka.dlt.retry.max.wait.ms=20000
app.kafka.dlt.retry.min.bytes=52428800

# Actuator stuff
## CIDR allowed to hit actuator
management.address=127.0.0.1

## Whether security should be enabled or disabled altogether
management.security.enabled=false

## CONSUMER ##
spring.kafka.consumer.group-id=group_id
spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE


spring.kafka.consumer.client-id=${KAFKA_CLIENT_ID:configure-me-client-id}
#spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:configure-me-group-id}
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.specific.avro.reader=true

## PRODUCER ##
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.client-id=${KAFKA_CLIENT_ID:configure-me-client-id}
spring.kafka.producer.acks=1
spring.kafka.producer.compression-type=lz4
spring.kafka.producer.properties.auto.register.schemas=true

## JDBC
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


